library/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('add',views.add,name='add'),
    path('edit/<int:id>',views.edit, name='edit'),
    path('update/<int:id>',views.update, name='update'),
    path('delete/<int:id>',views.delete, name='delete'),
]

myapp/models.py
from django.db import models
from isbn_field import ISBNField

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    publisher = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    date = models.DateField()
    isbn = ISBNField(clean_isbn=False,unique=True)

    def __str__(self):
        return self.title

myapp/forms.py
from django.forms import ModelForm
from django import forms
from myapp.models import Book

class DateInput(forms.DateInput):
    input_type = 'date'

class BooksForm(ModelForm):
    class Meta:
        model = Book
        fields = '__all__'
        required = '__all__'
        widgets = {
            'date': DateInput(),
        }

class DeleteBookForm(forms.Form):
    confirm = forms.BooleanField(required=True)

myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import BooksForm
from .models import Book
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.views.decorators.csrf import csrf_protect,csrf_exempt

# Create your views here.
@csrf_exempt
def index(request):
    if request.method=='GET' and 'submit' in request.GET:
        select = request.GET.get('select')
        search = request.GET.get('search')
        print(select)
        if select == 'title':
            book = Book.objects.filter(title__icontains=search)
        elif select == 'author':
            print("author",select)
            book = Book.objects.filter(author__icontains=search)
        elif select == 'category':
            book = Book.objects.filter(category__icontains=search)
        p = Paginator(book,4)
        num = request.GET.get('page', 1)
        try:
            page = p.page(num)
        except EmptyPage:
            page = p.page(1)
        except PageNotAnInteger:
            page = p.page(1)
        context = {'books':page,'search':search,'num':num,'p':p,'bool':True}
    else:
        book = Book.objects.all()
        p = Paginator(book,4)
        num = request.GET.get('page', 1)
        try:
            page = p.page(num)
        except EmptyPage:
            page = p.page(1)
        except PageNotAnInteger:
            page = p.page(1)
        context = {
            'books' : page,
            'num' : num,
            'p':p,
            'bool':False,
        }
    return render(request,'index.html',context=context)

@csrf_protect
def add(request):
    form = BooksForm()
    if request.method=='POST':
        form = BooksForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                messages.success(request,'Book added successfully !')
                return redirect('index')
            except ValidationError as e:
                messages.error(request,e.message)
    context = {'form':form}
    return render(request,'add.html',context=context)

@csrf_exempt
def edit(request,id):
    form = Book.objects.get(id=id)
    dic = {
        "form" : form,
        'id' : id,
        'date' : str(form.date)[::-1]
    }
    return render(request,'edit.html',dic)

@csrf_protect
@csrf_exempt
def update(request,id):
    if request.method=='POST':
        form = Book(id=id)
        form.title = request.POST['title']
        form.author = request.POST['author']
        form.publisher = request.POST['publisher']
        form.date = request.POST['date']
        form.isbn = request.POST['isbn']
        form.category = request.POST['category']
        form.save()
        messages.success(request, "Book details updated.")
        return redirect('index')

@csrf_protect
def delete(request,id):
    book = Book(id=id)
    if request.method=='POST':
        book.delete()
        messages.warning(request, "Book details deleted. ")
    return redirect('index')

myapp/templates/add.html
{% extends 'basic.html' %}
{% block css %}
.form-group{
    margin-top:1rem;
}
{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <center><h1 class="display-5" style="margin: 1rem auto;">Add Book Details</h1></center>
    <div class="row">
        <div class="col-md-6" style="margin:1rem auto;gap:10px;">
            <form action="{% url 'add' %}" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <center><button type="submit" class="btn btn-primary" style="margin: 1rem auto;">Submit</button></center>
            </form>
        </div>
    </div>
    
{% endblock %}

myapp/templates/basic.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Library Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>
      {% block css %}
      {% endblock %}
    </style>
  </head>
  <body style="overflow-x: hidden;">
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Library Management System</a>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'add' %}">Add Book</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

{% if messages %}
<div class="row">
  <div class="col-md-6" style="margin:1rem auto 0;">
        {% for message in messages %}
        {% if message.tags %}  {% endif %}
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{message}}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>

        {% endfor %}
  </div>
</div>
{% endif %}
    
{% block content %}
{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

myapp/templates/edit.html
{% extends 'basic.html' %}
{% block css %}
.form-group{
    margin-top:1rem;
}
{% endblock %}
{% block content %}
<center><h1 class="display-5" style="margin: 1rem auto 0;">Edit Book Details</h1></center>

<div class="row">
    <div class="col-md-6" style="margin:1rem auto 0;">
        <form action="/update/{{id}}" method="POST">
            <input type="hidden" name="csrfmiddlewaretoken" value="LDoD33tKgA6VQeCbVCz7qQF1KDsfA5u0K0EY7dJarjhajObxgPNLH4VtAq2bvvgx">
            

            <div id="div_id_title" class="form-group"> <label for="id_title" class=" requiredField">
            Title<span class="asteriskField">*</span> </label> <div> <input type="text" name="title" maxlength="200" class="textinput form-control" required="" id="id_title" value="{{form.title}}"> </div> </div>
            
            <div id="div_id_author" class="form-group"> <label for="id_author" class=" requiredField">
            Author<span class="asteriskField">*</span> </label> <div> <input type="text" name="author" maxlength="200" class="textinput form-control" required="" id="id_author" value="{{form.author}}"> </div> </div>
            
            <div id="div_id_publisher" class="form-group"> <label for="id_publisher" class=" requiredField">
            Publisher<span class="asteriskField">*</span> </label> <div> <input type="text" name="publisher" maxlength="200" class="textinput form-control" required="" id="id_publisher" value="{{form.publisher}}"> </div> </div>
            
            <div id="div_id_category" class="form-group"> <label for="id_category" class=" requiredField">
            Category<span class="asteriskField">*</span> </label> <div> <input type="text" name="category" maxlength="200" class="textinput form-control" required="" id="id_category" value="{{form.category}}"> </div> </div>
            
            <div id="div_id_date" class="form-group"> <label for="id_date" class=" requiredField">
            Date<span class="asteriskField">*</span> </label> <div> <input type="date" name="date" class="dateinput form-control" required="" id="id_date" value="{{date}}"> </div> </div>
            
            <div id="div_id_isbn" class="form-group"> <label for="id_isbn" class=" requiredField">
            ISBN<span class="asteriskField">*</span> </label> <div> <input type="text" name="isbn" maxlength="28" minlength="10" class="textinput form-control" required="" id="id_isbn" value="{{form.isbn}}"> </div> </div>

            <center><button type="submit" class="btn btn-outline-success" style="margin: 1rem auto;">Update</button></center>
        </form>
    </div>
</div>

{% endblock %}

myapp/templates/index.html
{% extends 'basic.html' %}


{% block content %}

<center><h1 class="display-5" style="margin: 1rem auto;">All Books List</h1></center>
<div class="row">
  <form class="d" role="search" method="GET" action="">
              <div class="col-md-6 " style="margin: 1rem auto;">
                  <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="select">
                      <option value="title">Book Title</option>
                      <option value="author">Book Author</option>
                      <option value="category">Category of the book</option>
                  </select>
              </div>
              <div class="col-md-6" style="margin:1rem auto;">
              <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Search" aria-label="Recipient's username" aria-describedby="button-addon2" name="search">
                <button class="btn btn-outline-success" type="submit" id="button-addon2" name="submit">Search</button>
              </div>
            </div>
            </form>
</div>
{% if books|length < 1 %}
{% if bool %}
  <center>
        <h3 class="diaplay-6" style="margin:1rem auto;">Please enter valid search query </h3>
        <p class="lead">No results matching : <b>{{search}} </b></p>
      </center>
    {% else %}
    <center><h3 class="diaplay-6" style="margin:1rem auto;">Currently no books ... </h3></center>
{% endif %}
{% else %}
<div class="row">
    <div class="col-md-10" style="margin: 1rem auto 0;">

        <table class="table">
            <thead>
              <tr>
                <th scope="col">Book ID</th>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">Publisher</th>
                <th scope="col">Publication Date</th>
                <th scope="col">ISBN</th>
                <th scope="col">Category</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for book in books %}
              <tr>
                <th scope="row">{{book.id}}</th>
                <td>{{book.title}}</td>
                <td>{{book.author}}</td>
                <td>{{book.publisher}}</td>
                <td>{{book.date}}</td>
                <td>{{book.isbn}}</td>
                <td>{{book.category}}</td>
                <td>
                  <form action="{% url 'delete' id=book.id %}" method="POST">
                    {% csrf_token %}
                    <a href="edit/{{book.id}}" class="btn btn-info">Edit</a>
                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this book ? ')">Delete</button>
                  </form>
                  <!-- <a href="delete/{{book.id}}" onclick="return confirm('Are you sure you want to delete this book ? ')" class="btn btn-danger">Delete</a> -->
                </td>
              </tr>
              {% endfor %}
              
            </tbody>
          </table>



    </div>
</div>
{% endif %}

<div class="row">
  <div class="col-md-6" style="margin:1rem auto;position: relative;">
    {% if books.has_previous %}
    <a href="{% url 'index' %}?page={{books.previous_page_number}}" class="btn btn-outline-primary" style="position: absolute; left: 0;">Previous Page</a>
    {% endif %}
    {% if books|length > 0 %}
    <p class="lead" style="position: absolute; left: 50%; transform: translateX(-50%);">
      Page {{num}} of {{p.num_pages}}
    </p>
    {% endif %}
    {% if books.has_next %}
    <a href="{% url 'index' %}?page={{books.next_page_number}}" class="btn btn-outline-primary" style="position: absolute; right: 0;">Next Page</a>
    {% endif %}
  </div>
</div>


{% endblock %}